# Generated by Django 4.2.29 on 2026-03-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full project name e.h. 'Customer Portal Redesign Q3 2024'.", max_length=200)),
                ('code', models.CharField(help_text="Unique project ode used in Task IDs , e.g 'CPR-2024'.", max_length=20, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the project scope and goals.')),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNING', help_text='Current lifecycle stage of the project.', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Business priority level affecting resource allocation.', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of the project.')),
                ('end_date', models.DateField(blank=True, help_text='Target completion date for the project.', null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text="approved project budget in the company's base currency", max_digits=14, null=True)),
                ('spent_budget', models.DecimalField(decimal_places=2, default=0, help_text='amount of money spent to date. Updated as costs are logged.', max_digits=14)),
                ('github_url', models.URLField(blank=True, help_text="Link to the project's Github repository", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive projects are archived and hidden from dashboards.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_manager', models.ForeignKey(help_text='The employee responsible for delivering this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=' the title of the task.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what needs to be done.', null=True)),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('IN_REVIEW', 'In Review'), ('DONE', 'Done'), ('BLOCKED', 'Blocked')], default='BACKLOG', help_text='Current stage of the task in the workflow.', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Urgency/importance of this task.', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Target completion date for this task.', null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours to complete this task.', max_digits=6, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Actual hours spent on this task(logged by assignee).', max_digits=6, null=True)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags for filtering , e.g 'backend, api, bug'.", max_length=255)),
                ('completed_at', models.DateField(blank=True, help_text='Timestamp when the task moved to DONE status.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='The employee responsible for completing this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='hr.employee')),
                ('created_by', models.ForeignKey(help_text='The employee who created this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='hr.employee')),
                ('project', models.ForeignKey(help_text='The Project this tasks belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_management.project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-priority', 'due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The content of the comment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='The employee who wrote this comment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_comments', to='hr.employee')),
                ('task', models.ForeignKey(help_text='The task this comment is given to.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project_management.task')),
            ],
            options={
                'verbose_name': 'Task Comment',
                'verbose_name_plural': 'Task Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MANAGER', 'Project Manager'), ('TECH LEAD', 'Technical Lead'), ('DEVELOPER', 'Developer'), ('DESIGNER', 'Designer / UX'), ('QA', 'Quality Assurance'), ('ANALYST', 'Business Analyst'), ('STAKEHOLDER', 'Stakeholder')], default='DEVELOPER', help_text="The employee's role within this specific project.", max_length=20)),
                ('joined_at', models.DateField(auto_now_add=True, help_text='Date the employee was added to this project.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive if the employee has left the project team.')),
                ('employee', models.ForeignKey(help_text='The employee who is a member of this project', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='hr.employee')),
                ('project', models.ForeignKey(help_text='The project this membership record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project_management.project')),
            ],
            options={
                'verbose_name': ('Project Member',),
                'verbose_name_plural': 'Project Members',
                'ordering': ['project', 'role'],
                'unique_together': {('project', 'employee')},
            },
        ),
    ]
