# Generated by Django 4.2.29 on 2026-03-16 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full department name, e.g. 'Engineering' or 'Finance'.", max_length=100, unique=True)),
                ('code', models.CharField(help_text="Short uppercase code used in reports, e.g. 'ENG' or 'FIN'.", max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text="Optional description of the department's purpose, responsibilities, or scope.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=" Official job title , e.g. 'Senior Software Engineer'.", max_length=150, unique=True)),
                ('level', models.CharField(choices=[('JUNIOR', 'Junior'), ('MID', 'Mid-Level'), ('SENIOR', 'Senior'), ('LEAD', 'Lead / Principal'), ('MANAGER', 'Manager'), ('DIRECTOR', 'Director')], help_text=' Seniority level of this position .', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of duties and expectations.', null=True)),
                ('min_salary', models.DecimalField(decimal_places=2, help_text='Minimum gross salary for this position.', max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, help_text='Maximum gross monthly salary for this position.', max_digits=10)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='The department this position belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='hr.department')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['department', 'level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text="Human-readable ID shown on badges , e.g 'EMP-2024-001", max_length=20, unique=True)),
                ('first_name', models.CharField(help_text="Employee's legal first name.", max_length=50)),
                ('last_name', models.CharField(help_text="Employee's legal surname.", max_length=50)),
                ('email', models.EmailField(help_text='Unique work email address for the employee.', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Primary phone number for contacting the employee.', max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="Employee's date of birth.", null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], help_text="Employee's self identified gender.", max_length=30)),
                ('national_id', models.CharField(blank=True, help_text='National ID card or passport number for payroll compliance.', max_length=30, null=True, unique=True)),
                ('address', models.TextField(blank=True, help_text='Residential or mailing address of the employee.', null=True)),
                ('profile_photo', models.ImageField(blank=True, help_text='Staff profile photo (JPEG or PNG , max 2 MB).', null=True, upload_to='employees/photos/')),
                ('hire_date', models.DateField(help_text='Official date when the employee joined the organization.')),
                ('end_date', models.DateField(blank=True, help_text='Termination date. Null if currently employed.', null=True)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full_Time'), ('PART_TIME', 'Part_Time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')], default='FULL_TIME', help_text='The nature of the employment contract.', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='ACTIVE', help_text='Current employment status of the employee.', max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Current salary amount paid to the employee.', max_digits=12, null=True)),
                ('bank_account', models.CharField(blank=True, help_text='Bank account for salary disbursement.', max_length=50, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, help_text="Full name of the employee's emergency contact person.", max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text="Phone number of the employee's emergency contact person.", max_length=20)),
                ('leave_balance', models.PositiveIntegerField(default=21, help_text='Number of annual leave days remaining.Reset to company policy value at start of each year.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department where the employee is currently assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.department')),
                ('manager', models.ForeignKey(blank=True, help_text="The employee's direct line manager. Null for top-level staff.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='hr.employee')),
                ('position', models.ForeignKey(blank=True, help_text='Position or job role currently held by the employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.position')),
                ('user', models.OneToOneField(help_text='System user account linked to this employee profile.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='The employee who leads this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to='hr.employee'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='hr_employee_employe_ec40c6_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='hr_employee_email_8e105e_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='hr_employee_status_75bd6c_idx'),
        ),
    ]
