# Generated by Django 4.2.29 on 2026-03-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name shown to employees, e.g 'Annual Leave'.", max_length=100, unique=True)),
                ('code', models.CharField(help_text="Short code used in reports and exports , e.g. 'AL', 'SL'.", max_length=20, unique=True)),
                ('max_days_per_year', models.PositiveIntegerField(help_text='Maximum  number of days that an employee can take a leave for.')),
                ('requires_approval', models.BooleanField(default=True, help_text='if true, a manager must approve before leave is granted')),
                ('is_paid', models.BooleanField(default=True, help_text='Whether the employee receives full payduring this leave')),
                ('description', models.TextField(blank=True, help_text='Policy notes and eligibility rules for this leave type.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive leave types are hidden from employee applications.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First Day of the requested leave(inclusive).')),
                ('end_date', models.DateField(help_text='Last Day of the requested leave(inclusive).')),
                ('total_days', models.PositiveIntegerField(default=0, editable=False, help_text='Automatically calculates number of calendar daysExcludes weekends if configured')),
                ('reason', models.TextField(help_text="Employee's written explanation for their leave request.")),
                ('status', models.CharField(choices=[('PENDING', 'Pending Request'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by Employee')], default='PENDING', help_text='current state in the approval workflow', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp of when the review decision was made', null=True)),
                ('review_comment', models.TextField(blank=True, help_text='Optional note from the reviewer explaining the decision.', null=True)),
                ('attachment', models.FileField(blank=True, help_text='Supporting document , e.g medical certificate', null=True, upload_to='leave/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='The employee who submitted the leave request', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee')),
                ('leave_type', models.ForeignKey(help_text='The type of leave request', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='leave_management.leavetype')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Manager who took the approval/reject decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to='hr.employee')),
            ],
            options={
                'verbose_name': ('Leave Request',),
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='leave_manag_status_739e47_idx'), models.Index(fields=['employee', 'status'], name='leave_manag_employe_76bff2_idx')],
            },
        ),
    ]
