# Generated by Django 4.2.29 on 2026-03-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Calendar date of this attendance entry.only one record per employee per day is allowed')),
                ('check_in', models.DateTimeField(blank=True, help_text='Exact timestamp when the employee clocked in for the day.', null=True)),
                ('check_out', models.DateTimeField(blank=True, help_text='Exact timestamp when the employee clocked out.Null if the employee has not yet checked out', null=True)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='computed hours worked(checkout - checkincalculated automatically on save', max_digits=8, null=True)),
                ('overtime_hours', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Hours worked beyond STANDARD_HOURS(8 hrs).Calculated automatically', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late Arrival'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Approved Leave')], default='PRESENT', help_text='Attendance status for the day', max_length=10)),
                ('location', models.CharField(blank=True, choices=[('OFFICE', 'Office'), ('REMOTE', 'Remote / Work From Home'), ('FIELD', 'Field /On-Site')], help_text='where the employee was working is from', max_length=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Ip address captured at check-in for audit purposes', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional comments from the employee or HR manager.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='tThe employee this attendance record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee')),
            ],
            options={
                'verbose_name': ('Attendance Record',),
                'verbose_name_plural': ('Attendance Records',),
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance__employe_b6a945_idx'), models.Index(fields=['date', 'status'], name='attendance__date_64c311_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
